In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,25,10)
a

array([13, 15,  8, 10, 24, 14, 22, 20,  1, 19])

In [5]:
b = a.reshape(2,5)
b

array([[13, 15,  8, 10, 24],
       [14, 22, 20,  1, 19]])

In [8]:
b.shape

(2, 5)

In [9]:
a.shape

(10,)

In [10]:
c = np.random.randint(0,25,10).reshape(2,5).shape
c

(2, 5)

In [11]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
arr.shape

(25,)

In [13]:
arr[5]

5

In [14]:
arr[2:5]

array([2, 3, 4])

In [15]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[:5]

array([0, 1, 2, 3, 4])

In [17]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
arr[10:1]

array([], dtype=int32)

In [20]:
arr[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr[10:25]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
e = np.eye(5,3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
rnum = np.random.rand(10)
rnum

array([0.61708104, 0.21600521, 0.11403411, 0.7775305 , 0.09005909,
       0.2089061 , 0.3675522 , 0.46553836, 0.76993848, 0.20051743])

In [27]:
rnnum = np.random.randn(10)
rnnum

array([-0.55947687,  1.17352773,  1.97341444,  0.82975081,  1.04398738,
       -0.14481308,  0.62701925, -0.95065856, -1.68692196, -0.54359376])

In [28]:
rnum.dtype

dtype('float64')

In [29]:
arr.dtype

dtype('int32')

In [32]:
zer1 = np.zeros(4)
zer1

array([0., 0., 0., 0.])

In [35]:
zer2 = zer1.reshape(2,2)
zer2

array([[0., 0.],
       [0., 0.]])

In [37]:
one1 = np.ones(4)
one1

array([1., 1., 1., 1.])

In [41]:
one2 = one1.reshape(2,2)
one2

array([[1., 1.],
       [1., 1.]])

In [43]:
arr.min()

0

In [44]:
arr.max()

24

In [45]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr2 = arr1[0:5]
arr2

array([0, 1, 2, 3, 4])

In [50]:
arr2[:] = 99# it will also change the original array from which it created.

In [51]:
arr2

array([99, 99, 99, 99, 99])

In [52]:
arr1 # since arr2 was changed its values to 99 so arr1 was also changed.

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [54]:
arr3 = arr1.copy() # it will create a new copy of arr1 with its values and saved in different memory location
arr3

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [55]:
arr1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])